"""change firm_stats value to integer

Revision ID: 2f920be14e3c
Revises: b42d1feb2796
Create Date: 2026-08-03 18:38:41.698559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f920be14e3c'
down_revision = 'b42d1feb2796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firm_stats', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firm_stats', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40),
               existing_nullable=False)

    # ### end Alembic commands ###
