"""add batch to articles

Revision ID: 8257cd848c16
Revises: 9138c58e391e
Create Date: 2026-08-01 18:04:36.938879

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8257cd848c16'
down_revision = '9138c58e391e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###
    # Note: autogenerate also detected pre-existing drift (a leftover
    # 'core_values' table and stale 'services' indexes) unrelated to this
    # change - intentionally left out, same convention as de4963600900.


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('batch')
    # ### end Alembic commands ###
