"""add articles table

Revision ID: 9138c58e391e
Revises: de4963600900
Create Date: 2026-08-01 17:37:18.558328

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9138c58e391e'
down_revision = 'de4963600900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('thumbnail', sa.String(length=500), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', name='article_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_status'), ['status'], unique=False)
    # ### end Alembic commands ###
    # Note: autogenerate also detected pre-existing drift (a leftover
    # 'core_values' table and stale 'services' indexes) unrelated to this
    # change - intentionally left out of this migration so it stays scoped
    # to articles only, same convention as de4963600900.


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_status'))

    op.drop_table('articles')
    # ### end Alembic commands ###
