"""add sync source and nullable phone to appointments

Revision ID: ae30663fcf35
Revises: 2f920be14e3c
Create Date: 2026-08-05 11:09:11.101253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae30663fcf35'
down_revision = '2f920be14e3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('client_phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               nullable=True)
        batch_op.alter_column('source',
               existing_type=mysql.ENUM('embed', 'webhook', 'admin', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('embed', 'webhook', 'admin', 'sync', name='appointment_source'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.Enum('embed', 'webhook', 'admin', 'sync', name='appointment_source'),
               type_=mysql.ENUM('embed', 'webhook', 'admin', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
        batch_op.alter_column('client_phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               nullable=False)

    # ### end Alembic commands ###
