"""add status to newsletter_campaigns

Revision ID: b42d1feb2796
Revises: d89c119aede3
Create Date: 2026-08-03 16:39:12.815884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b42d1feb2796'
down_revision = 'd89c119aede3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter_campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('sending', 'sent', name='newsletter_campaign_status'), server_default='sent', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter_campaigns', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
