"""add designation to articles

Revision ID: b8c1c053a197
Revises: 8257cd848c16
Create Date: 2026-08-01 18:16:45.472529

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b8c1c053a197'
down_revision = '8257cd848c16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designation', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###
    # Note: autogenerate also detected pre-existing drift (a leftover
    # 'core_values' table and stale 'services' indexes) unrelated to this
    # change - intentionally left out, same convention as de4963600900.


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('designation')
    # ### end Alembic commands ###
