"""add appointment mode and location detail

Revision ID: c1e2a69eabee
Revises: ae30663fcf35
Create Date: 2026-08-05 12:17:18.508928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1e2a69eabee'
down_revision = 'ae30663fcf35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_mode', sa.Enum('phone', 'zoom', 'in_person', 'other', name='appointment_mode'), nullable=True))
        batch_op.add_column(sa.Column('location_detail', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('location_detail')
        batch_op.drop_column('appointment_mode')

    # ### end Alembic commands ###
