"""add appointments and webhook_events tables

Revision ID: de4963600900
Revises: f1a2b3c4d5e6
Create Date: 2026-07-31 15:37:57.665885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de4963600900'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendly_event_id', sa.String(length=100), nullable=True),
    sa.Column('calendly_event_uri', sa.String(length=500), nullable=True),
    sa.Column('calendly_invitee_uri', sa.String(length=500), nullable=True),
    sa.Column('calendly_invitee_id', sa.String(length=100), nullable=True),
    sa.Column('client_name', sa.String(length=120), nullable=False),
    sa.Column('client_email', sa.String(length=190), nullable=False),
    sa.Column('client_phone', sa.String(length=10), nullable=False),
    sa.Column('event_name', sa.String(length=200), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meeting_date', sa.Date(), nullable=True),
    sa.Column('meeting_time', sa.Time(), nullable=True),
    sa.Column('timezone', sa.String(length=60), nullable=True),
    sa.Column('meeting_link', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'cancelled', 'rescheduled', 'completed', name='appointment_status'), nullable=False),
    sa.Column('source', sa.Enum('embed', 'webhook', 'admin', name='appointment_source'), nullable=False),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('rescheduled_to_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reminder_24h_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_1h_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rescheduled_to_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_calendly_event_id'), ['calendly_event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_appointments_calendly_invitee_id'), ['calendly_invitee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_client_email'), ['client_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_starts_at'), ['starts_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_status'), ['status'], unique=False)

    op.create_table('webhook_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('received', 'processed', 'failed', 'duplicate', name='webhook_event_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_events_dedupe_key'), ['dedupe_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_webhook_events_status'), ['status'], unique=False)

    # ### end Alembic commands ###
    # Note: autogenerate also detected pre-existing drift on 'services'
    # indexes (ix_services_hero_background_media_id and two others) unrelated
    # to this change - intentionally left out of this migration so it stays
    # scoped to appointments/webhook_events only.


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_events_status'))
        batch_op.drop_index(batch_op.f('ix_webhook_events_dedupe_key'))
        batch_op.drop_index(batch_op.f('ix_webhook_events_created_at'))

    op.drop_table('webhook_events')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_status'))
        batch_op.drop_index(batch_op.f('ix_appointments_starts_at'))
        batch_op.drop_index(batch_op.f('ix_appointments_client_email'))
        batch_op.drop_index(batch_op.f('ix_appointments_calendly_invitee_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_calendly_event_id'))

    op.drop_table('appointments')
    # ### end Alembic commands ###
